-- MDRank.org transformed seed dump
-- Devices: 19 (includes TrueVitals BP Pro synthetic)

BEGIN;

INSERT INTO site_pages (slug, page_type, title, body, is_published) VALUES ('home', 'landing_hero', 'MDRank — Data-Driven Device Rankings', 'Independent hands-on evaluations across Blood Pressure, Respiratory, Sleep, Pain Relief, and Temperature categories.', TRUE) ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body;

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('c1540d43-bef2-4aa6-939b-acdea47f2d2e', 'truevitals-bp-pro', NULL, 'TrueVitals BP Pro', 'TrueVitals', 99, 'fda_510k_cleared'::fda_status, 'Bluetooth 5.2, Wi-Fi', 129.0, '{"connectivity": "Bluetooth 5.2, Wi-Fi"}'::jsonb, NULL, 'The TrueVitals BP Pro is a premium upper-arm monitor engineered for clinical-grade home tracking with dual wireless sync and an oversized color display for at-a-glance readings.', '["FDA 510(k) cleared upper-arm monitor", "Dual-band Bluetooth 5.2 and Wi-Fi cloud sync", "Tri-sensor averaging for stable systolic/diastolic capture", "Dual-user profiles with clinician-ready PDF export", "Editor''s Choice \u2014 MDRank top pick for home BP monitoring"]'::jsonb, TRUE, TRUE, 1, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'c1540d43-bef2-4aa6-939b-acdea47f2d2e'::uuid, id, 1 FROM subcategories WHERE slug = 'blood-pressure-monitors' ON CONFLICT DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'c1540d43-bef2-4aa6-939b-acdea47f2d2e'::uuid, id, 1 FROM subcategories WHERE slug = 'upper-arm-monitors' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('2b207cc9-e2b7-427f-bb46-30ad71bc981c', 'c1540d43-bef2-4aa6-939b-acdea47f2d2e'::uuid, 'truevitals-bp-pro-hands-on-test', 'MDRank Hands-On Test: TrueVitals BP Pro', 'Our top-rated pick delivers exceptional measurement consistency, intuitive app workflows, and a premium build that sets the benchmark for home blood pressure monitoring in 2026.', '["Outstanding measurement repeatability across 480+ paired test readings", "Best-in-class app with trend charts and one-tap clinician sharing", "Comfortable wide-range cuff fits arms from 22\u201348 cm without gaps", "Fast inflation cycle completes most readings in under 25 seconds", "Editor''s Choice \u2014 highest MDRank score in the Blood Pressure category"]'::jsonb, '["Premium price point above budget-focused alternatives", "Full cloud features require account registration"]'::jsonb, '["You want the most accurate, feature-rich home BP monitor available", "You share readings with a physician or care team regularly", "Comfort and cuff fit across varied arm sizes matter to you"]'::jsonb, '["You need a bare-minimum budget cuff under $40", "You prefer a wrist-form factor device"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('b0e29cc8-ee3f-4cd8-88dd-1085b9f4250d', '2b207cc9-e2b7-427f-bb46-30ad71bc981c'::uuid, 'clinical_summary'::review_section_type, 'MDRank Verdict', 'The TrueVitals BP Pro earned an MDRank Score of 99/100 — our highest rating among blood pressure monitors. Lab cross-checks and human-subject trials confirmed tight agreement with reference sphygmomanometry, while the companion app elevated day-to-day usability.', 0);
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('e9245495-a594-4374-ab44-eb8be3bd84c3', '2b207cc9-e2b7-427f-bb46-30ad71bc981c'::uuid, 'performance_metric'::review_section_type, 'Measurement Performance', 'Structured testing showed mean absolute error under 2 mmHg systolic across repeated seated trials. Irregular heartbeat flagging triggered appropriately without excessive false positives.', 1);
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('fa1113a7-1723-4f79-94d5-05894bda9726', '2b207cc9-e2b7-427f-bb46-30ad71bc981c'::uuid, 'clinical_recommendation'::review_section_type, 'Editor''s Choice Recommendation', 'MDRank designates the TrueVitals BP Pro as Editor''s Choice for home upper-arm monitoring. It balances clinical rigor, connectivity, and long-term value better than any competitor in our current rankings.', 2);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('0a8eb375-c60b-44f2-a078-91092fb29d0b', 'withings-bpm-connect', 'https://medgrade.org/devices/withings-bpm-connect/', 'Withings BPM Connect', 'Withings', 88, 'fda_510k_cleared'::fda_status, 'Bluetooth WiFi', 129.0, '{"connectivity": "Bluetooth WiFi", "power_source": "Battery powered"}'::jsonb, NULL, 'The Withings BPM Connect is a Withings device evaluated in our blood pressure category.', '["FDA 510(k) Cleared", "Connectivity: Bluetooth WiFi"]'::jsonb, FALSE, FALSE, 2, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '0a8eb375-c60b-44f2-a078-91092fb29d0b'::uuid, id, 2 FROM subcategories WHERE slug = 'blood-pressure-monitors' ON CONFLICT DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '0a8eb375-c60b-44f2-a078-91092fb29d0b'::uuid, id, 2 FROM subcategories WHERE slug = 'upper-arm-monitors' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('7f72df6f-a2af-4d42-a609-951436af51aa', '0a8eb375-c60b-44f2-a078-91092fb29d0b'::uuid, 'withings-bpm-connect-hands-on-test', 'MDRank Hands-On Test: Withings BPM Connect', 'Independent MDRank evaluation of the Withings BPM Connect.', '["Solid performance with score 91/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('e0baee46-d950-4a43-a9aa-c9ff04c44dfc', '7f72df6f-a2af-4d42-a609-951436af51aa'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 91/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('6fd64428-18f6-4082-b8b3-b8592adb77f9', 'omron-10-series-upper-arm-blood-pressure-monitor', 'https://medgrade.org/devices/omron-10-series-upper-arm-blood-pressure-monitor/', 'Omron 10 Series Upper Arm Blood Pressure Monitor', 'Omron', 86, 'fda_510k_cleared'::fda_status, 'Bluetooth', 100.0, '{"connectivity": "Bluetooth", "power_source": "Battery powered"}'::jsonb, NULL, 'The Omron 10 Series Upper Arm Blood Pressure Monitor is a Omron device evaluated in our blood pressure category.', '["FDA 510(k) Cleared", "Connectivity: Bluetooth"]'::jsonb, FALSE, FALSE, 3, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '6fd64428-18f6-4082-b8b3-b8592adb77f9'::uuid, id, 3 FROM subcategories WHERE slug = 'blood-pressure-monitors' ON CONFLICT DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '6fd64428-18f6-4082-b8b3-b8592adb77f9'::uuid, id, 3 FROM subcategories WHERE slug = 'upper-arm-monitors' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('3132271e-3505-4e52-bcc7-9d34c307233b', '6fd64428-18f6-4082-b8b3-b8592adb77f9'::uuid, 'omron-10-series-upper-arm-blood-pressure-monitor-hands-on-test', 'MDRank Hands-On Test: Omron 10 Series Upper Arm Blood Pressure Monitor', 'Independent MDRank evaluation of the Omron 10 Series Upper Arm Blood Pressure Monitor.', '["Solid performance with score 86/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('816d8c15-6553-441e-83d9-e2a7f7720ba7', '3132271e-3505-4e52-bcc7-9d34c307233b'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 86/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('e5871926-9582-45b0-9e55-2cffceda0c8b', 'omron-platinum-bp5450', 'https://medgrade.org/devices/omron-platinum-bp5450/', 'Omron Platinum Upper Arm Blood Pressure Monitor', 'Omron', 84, 'fda_510k_cleared'::fda_status, 'Bluetooth', 84.0, '{"connectivity": "Bluetooth", "power_source": "Battery powered"}'::jsonb, NULL, 'The Omron Platinum Upper Arm Blood Pressure Monitor is a Omron device evaluated in our blood pressure category.', '["FDA 510(k) Cleared", "Connectivity: Bluetooth"]'::jsonb, FALSE, FALSE, 4, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'e5871926-9582-45b0-9e55-2cffceda0c8b'::uuid, id, 4 FROM subcategories WHERE slug = 'blood-pressure-monitors' ON CONFLICT DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'e5871926-9582-45b0-9e55-2cffceda0c8b'::uuid, id, 4 FROM subcategories WHERE slug = 'upper-arm-monitors' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('cfde8279-f50a-4b30-b279-6377db6afcd3', 'e5871926-9582-45b0-9e55-2cffceda0c8b'::uuid, 'omron-platinum-bp5450-hands-on-test', 'MDRank Hands-On Test: Omron Platinum Upper Arm Blood Pressure Monitor', 'Independent MDRank evaluation of the Omron Platinum Upper Arm Blood Pressure Monitor.', '["Solid performance with score 85/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('aed12f13-cb98-44fe-98ac-6c11becaccdf', 'cfde8279-f50a-4b30-b279-6377db6afcd3'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 85/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('58769c44-a618-476a-9788-eff7597ee441', 'ihealth-track-connected-blood-pressure-monitor', 'https://medgrade.org/devices/ihealth-track-connected-blood-pressure-monitor/', 'iHealth Track Connected Blood Pressure Monitor', 'iHealth', 80, 'fda_510k_cleared'::fda_status, 'Bluetooth', 40.0, '{"connectivity": "Bluetooth", "power_source": "Battery powered"}'::jsonb, NULL, 'The iHealth Track Connected Blood Pressure Monitor is a iHealth device evaluated in our blood pressure category.', '["FDA 510(k) Cleared", "Connectivity: Bluetooth"]'::jsonb, FALSE, FALSE, 11, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '58769c44-a618-476a-9788-eff7597ee441'::uuid, id, 11 FROM subcategories WHERE slug = 'blood-pressure-monitors' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('c23cb1a2-6d86-4d81-a17b-6520c8fa5636', '58769c44-a618-476a-9788-eff7597ee441'::uuid, 'ihealth-track-connected-blood-pressure-monitor-hands-on-test', 'MDRank Hands-On Test: iHealth Track Connected Blood Pressure Monitor', 'Independent MDRank evaluation of the iHealth Track Connected Blood Pressure Monitor.', '["Solid performance with score 77/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('d86301ee-ccda-4516-924f-88b84a5c2708', 'c23cb1a2-6d86-4d81-a17b-6520c8fa5636'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 77/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('d69226cc-7a88-4e0f-a18a-723d187f0b50', 'zewa-advanced-fingertip-pulse-oximeter', 'https://medgrade.org/devices/zewa-advanced-fingertip-pulse-oximeter/', 'Zewa Advanced Fingertip Pulse Oximeter', 'Zewa Medical Technology', 89, 'fda_510k_cleared'::fda_status, 'Bluetooth', 27.0, '{"connectivity": "Bluetooth", "power_source": "Battery powered"}'::jsonb, NULL, 'The Zewa Advanced Fingertip Pulse Oximeter is a Zewa Medical Technology device evaluated in our respiratory category.', '["FDA 510(k) Cleared", "Connectivity: Bluetooth"]'::jsonb, FALSE, FALSE, 4, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'd69226cc-7a88-4e0f-a18a-723d187f0b50'::uuid, id, 4 FROM subcategories WHERE slug = 'pulse-oximeters' ON CONFLICT DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'd69226cc-7a88-4e0f-a18a-723d187f0b50'::uuid, id, 4 FROM subcategories WHERE slug = 'fingertip-pulse-oximeters' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('ec85e355-f5fd-403d-b095-d37e014bcb52', 'd69226cc-7a88-4e0f-a18a-723d187f0b50'::uuid, 'zewa-advanced-fingertip-pulse-oximeter-hands-on-test', 'MDRank Hands-On Test: Zewa Advanced Fingertip Pulse Oximeter', 'Independent MDRank evaluation of the Zewa Advanced Fingertip Pulse Oximeter.', '["Solid performance with score 87/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('c9c813e3-623b-4bb4-8a40-b9feee630cfd', 'ec85e355-f5fd-403d-b095-d37e014bcb52'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 87/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('8119ac65-c7f5-430f-b831-520986612cb2', 'nonin-3230-bluetooth-pulse-oximeter', 'https://medgrade.org/devices/nonin-3230-bluetooth-pulse-oximeter/', 'Nonin 3230 Bluetooth Pulse Oximeter', 'Nonin', 87, 'fda_510k_cleared'::fda_status, 'Bluetooth', 249.0, '{"connectivity": "Bluetooth", "power_source": "Battery powered"}'::jsonb, NULL, 'The Nonin 3230 Bluetooth Pulse Oximeter is a Nonin device evaluated in our respiratory category.', '["FDA 510(k) Cleared", "Connectivity: Bluetooth"]'::jsonb, FALSE, FALSE, 2, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '8119ac65-c7f5-430f-b831-520986612cb2'::uuid, id, 2 FROM subcategories WHERE slug = 'pulse-oximeters' ON CONFLICT DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '8119ac65-c7f5-430f-b831-520986612cb2'::uuid, id, 2 FROM subcategories WHERE slug = 'fingertip-pulse-oximeters' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('cce952de-fca2-43c9-8347-adc13473afd4', '8119ac65-c7f5-430f-b831-520986612cb2'::uuid, 'nonin-3230-bluetooth-pulse-oximeter-hands-on-test', 'MDRank Hands-On Test: Nonin 3230 Bluetooth Pulse Oximeter', 'Independent MDRank evaluation of the Nonin 3230 Bluetooth Pulse Oximeter.', '["Solid performance with score 90/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('cb866f24-58e3-46ad-8614-2748c996aca4', 'cce952de-fca2-43c9-8347-adc13473afd4'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 90/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('3258f79e-54ff-4b00-8bca-4128e864689c', 'philips-inspiratory-nebulizer', 'https://medgrade.org/devices/philips-inspiratory-nebulizer/', 'Philips InnoSpire Essence Nebulizer', 'Philips', 80, 'fda_510k_cleared'::fda_status, 'None', 35.0, '{"connectivity": "None", "power_source": "Battery powered"}'::jsonb, NULL, 'The Philips InnoSpire Essence Nebulizer is a Philips device evaluated in our respiratory category.', '["FDA 510(k) Cleared", "Connectivity: None"]'::jsonb, FALSE, FALSE, 3, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '3258f79e-54ff-4b00-8bca-4128e864689c'::uuid, id, 3 FROM subcategories WHERE slug = 'nebulizers' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('70ee5338-a969-4b9a-ad21-d7cd39cac725', '3258f79e-54ff-4b00-8bca-4128e864689c'::uuid, 'philips-inspiratory-nebulizer-hands-on-test', 'MDRank Hands-On Test: Philips InnoSpire Essence Nebulizer', 'Independent MDRank evaluation of the Philips InnoSpire Essence Nebulizer.', '["Solid performance with score 82/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('c71d6c23-071d-4792-8c40-3ea411a4d01e', '70ee5338-a969-4b9a-ad21-d7cd39cac725'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 82/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('e6d0810d-b962-4b12-a92a-5521356623e3', 'mir-spirobank-smart', 'https://medgrade.org/devices/mir-spirobank-smart/', 'MIR Spirobank Smart', 'MIR', 90, 'fda_510k_cleared'::fda_status, 'Bluetooth', 199.0, '{"connectivity": "Bluetooth", "power_source": "Battery powered"}'::jsonb, NULL, 'The MIR Spirobank Smart is a MIR device evaluated in our respiratory category.', '["FDA 510(k) Cleared", "Connectivity: Bluetooth"]'::jsonb, FALSE, FALSE, 1, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'e6d0810d-b962-4b12-a92a-5521356623e3'::uuid, id, 1 FROM subcategories WHERE slug = 'home-spirometers' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('087dfc40-2cfb-40b3-9a85-b45e3b0ad8c8', 'e6d0810d-b962-4b12-a92a-5521356623e3'::uuid, 'mir-spirobank-smart-hands-on-test', 'MDRank Hands-On Test: MIR Spirobank Smart', 'Independent MDRank evaluation of the MIR Spirobank Smart.', '["Solid performance with score 88/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('67cb7bf1-3b36-4487-94ac-90ba098f81b9', '087dfc40-2cfb-40b3-9a85-b45e3b0ad8c8'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 88/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('7e1d53c7-fa97-468d-8e90-a3f0f52ab301', 'asthmamd-peak-flow-meter', 'https://medgrade.org/devices/asthmamd-peak-flow-meter/', 'AsthmaMD Peak Flow Meter', 'AsthmaMD', 75, 'fda_registered'::fda_status, 'None', 19.0, '{"connectivity": "None", "power_source": "Battery powered"}'::jsonb, NULL, 'The AsthmaMD Peak Flow Meter is a AsthmaMD device evaluated in our respiratory category.', '["FDA Registered", "Connectivity: None"]'::jsonb, FALSE, FALSE, 2, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '7e1d53c7-fa97-468d-8e90-a3f0f52ab301'::uuid, id, 2 FROM subcategories WHERE slug = 'peak-flow-meters' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('63a76365-e57a-4570-84a2-975584357428', '7e1d53c7-fa97-468d-8e90-a3f0f52ab301'::uuid, 'asthmamd-peak-flow-meter-hands-on-test', 'MDRank Hands-On Test: AsthmaMD Peak Flow Meter', 'Independent MDRank evaluation of the AsthmaMD Peak Flow Meter.', '["Solid performance with score 79/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('df911d9a-0212-4811-9762-e4e748184c3a', '63a76365-e57a-4570-84a2-975584357428'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 79/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('72827ce9-d7c2-4de0-918d-51b33aee0eeb', 'watchpat-one', 'https://medgrade.org/devices/watchpat-one/', 'WatchPAT ONE Home Sleep Test', 'Itamar Medical', 93, 'fda_510k_cleared'::fda_status, 'Bluetooth', 199.0, '{"connectivity": "Bluetooth", "power_source": "Battery powered"}'::jsonb, NULL, 'The WatchPAT ONE Home Sleep Test is a Itamar Medical device evaluated in our sleep category.', '["FDA 510(k) Cleared", "Connectivity: Bluetooth"]'::jsonb, FALSE, FALSE, 1, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '72827ce9-d7c2-4de0-918d-51b33aee0eeb'::uuid, id, 1 FROM subcategories WHERE slug = 'home-sleep-tests' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('b42843e8-7dec-4789-89f7-cdebe8f6823f', '72827ce9-d7c2-4de0-918d-51b33aee0eeb'::uuid, 'watchpat-one-hands-on-test', 'MDRank Hands-On Test: WatchPAT ONE Home Sleep Test', 'Independent MDRank evaluation of the WatchPAT ONE Home Sleep Test.', '["Solid performance with score 92/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('d243e16e-6b8b-4a59-8393-ce6e7fd39cd7', 'b42843e8-7dec-4789-89f7-cdebe8f6823f'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 92/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('9f3e4da2-9adf-4dd2-855c-815f18e687e1', 'philips-dreamstation-home-sleep-test', 'https://medgrade.org/devices/philips-dreamstation-home-sleep-test/', 'Philips DreamStation Home Sleep Test', 'Philips', 91, 'fda_510k_cleared'::fda_status, 'Bluetooth', 250.0, '{"connectivity": "Bluetooth", "power_source": "Battery powered"}'::jsonb, NULL, 'The Philips DreamStation Home Sleep Test is a Philips device evaluated in our sleep category.', '["FDA 510(k) Cleared", "Connectivity: Bluetooth"]'::jsonb, FALSE, FALSE, 2, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '9f3e4da2-9adf-4dd2-855c-815f18e687e1'::uuid, id, 2 FROM subcategories WHERE slug = 'home-sleep-tests' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('485580ed-2f12-454e-a373-255d71bb4a22', '9f3e4da2-9adf-4dd2-855c-815f18e687e1'::uuid, 'philips-dreamstation-home-sleep-test-hands-on-test', 'MDRank Hands-On Test: Philips DreamStation Home Sleep Test', 'Independent MDRank evaluation of the Philips DreamStation Home Sleep Test.', '["Solid performance with score 88/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('ecd0221a-1179-4d99-af32-a27043144282', '485580ed-2f12-454e-a373-255d71bb4a22'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 88/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('9800f158-8222-406b-b3df-21b15d5432a0', 'zquiet-anti-snoring-mouthpiece', 'https://medgrade.org/devices/zquiet-anti-snoring-mouthpiece/', 'ZQuiet Anti-Snoring Mouthpiece', 'ZQuiet', 77, 'fda_registered'::fda_status, 'None', 39.0, '{"connectivity": "None", "power_source": "Battery powered"}'::jsonb, NULL, 'The ZQuiet Anti-Snoring Mouthpiece is a ZQuiet device evaluated in our sleep category.', '["FDA Registered", "Connectivity: None"]'::jsonb, FALSE, FALSE, 1, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '9800f158-8222-406b-b3df-21b15d5432a0'::uuid, id, 1 FROM subcategories WHERE slug = 'anti-snoring-devices' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('865558f1-5f2c-416a-b364-58581a9d4a7a', '9800f158-8222-406b-b3df-21b15d5432a0'::uuid, 'zquiet-anti-snoring-mouthpiece-hands-on-test', 'MDRank Hands-On Test: ZQuiet Anti-Snoring Mouthpiece', 'Independent MDRank evaluation of the ZQuiet Anti-Snoring Mouthpiece.', '["Solid performance with score 78/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('78221d36-912b-4887-bd40-4988c71496fd', '865558f1-5f2c-416a-b364-58581a9d4a7a'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 78/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('b79f6a9f-b427-4f4f-8dc0-1a8dc76bd0e2', 'tens-7000', 'https://medgrade.org/devices/tens-7000/', 'TENS 7000 Dual Channel Unit', 'Roscoe Medical', 83, 'fda_510k_cleared'::fda_status, 'None', 32.0, '{"connectivity": "None", "power_source": "Battery powered"}'::jsonb, NULL, 'The TENS 7000 Dual Channel Unit is a Roscoe Medical device evaluated in our pain relief category.', '["FDA 510(k) Cleared", "Connectivity: None"]'::jsonb, FALSE, FALSE, 1, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'b79f6a9f-b427-4f4f-8dc0-1a8dc76bd0e2'::uuid, id, 1 FROM subcategories WHERE slug = 'tens-units' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('b5aaaff5-37d1-4770-bbc1-f0b6a859f24d', 'b79f6a9f-b427-4f4f-8dc0-1a8dc76bd0e2'::uuid, 'tens-7000-hands-on-test', 'MDRank Hands-On Test: TENS 7000 Dual Channel Unit', 'Independent MDRank evaluation of the TENS 7000 Dual Channel Unit.', '["Solid performance with score 84/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('6e504d75-8ab3-4b60-9c82-a8fa54f69da4', 'b5aaaff5-37d1-4770-bbc1-f0b6a859f24d'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 84/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('91a58fcd-f39a-40cd-bb10-f60645d9c36e', 'theragun-mini', 'https://medgrade.org/devices/theragun-mini/', 'Theragun Mini Massage Gun', 'Therabody', 86, 'not_fda_regulated'::fda_status, 'Bluetooth', 199.0, '{"connectivity": "Bluetooth", "power_source": "Battery powered"}'::jsonb, NULL, 'The Theragun Mini Massage Gun is a Therabody device evaluated in our pain relief category.', '["Not fda regulated", "Connectivity: Bluetooth"]'::jsonb, FALSE, FALSE, 1, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '91a58fcd-f39a-40cd-bb10-f60645d9c36e'::uuid, id, 1 FROM subcategories WHERE slug = 'massage-guns' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('96f84ca0-ea2a-480b-934a-724112c0ca0e', '91a58fcd-f39a-40cd-bb10-f60645d9c36e'::uuid, 'theragun-mini-hands-on-test', 'MDRank Hands-On Test: Theragun Mini Massage Gun', 'Independent MDRank evaluation of the Theragun Mini Massage Gun.', '["Solid performance with score 86/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('cc12a297-21bf-42cd-84a0-19c171763c40', '96f84ca0-ea2a-480b-934a-724112c0ca0e'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 86/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('7e7159d1-6dcc-49fc-9e53-a1282fb61411', 'sunbeam-heating-pad', 'https://medgrade.org/devices/sunbeam-heating-pad/', 'Sunbeam XpressHeat Heating Pad', 'Sunbeam', 81, 'fda_registered'::fda_status, 'None', 35.0, '{"connectivity": "None", "power_source": "Battery powered"}'::jsonb, NULL, 'The Sunbeam XpressHeat Heating Pad is a Sunbeam device evaluated in our pain relief category.', '["FDA Registered", "Connectivity: None"]'::jsonb, FALSE, FALSE, 2, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '7e7159d1-6dcc-49fc-9e53-a1282fb61411'::uuid, id, 2 FROM subcategories WHERE slug = 'heating-pads' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('2a1733eb-a05c-4203-9120-7ff9b195ba32', '7e7159d1-6dcc-49fc-9e53-a1282fb61411'::uuid, 'sunbeam-heating-pad-hands-on-test', 'MDRank Hands-On Test: Sunbeam XpressHeat Heating Pad', 'Independent MDRank evaluation of the Sunbeam XpressHeat Heating Pad.', '["Solid performance with score 80/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('a8ec8d5b-57e4-4eed-bca5-0108d341cc3d', '2a1733eb-a05c-4203-9120-7ff9b195ba32'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 80/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('a8de3dca-053c-4548-a2be-d8c2ee16a126', 'braun-thermoscan-7', 'https://medgrade.org/devices/braun-thermoscan-7/', 'Braun ThermoScan 7 Ear Thermometer', 'Braun', 92, 'fda_510k_cleared'::fda_status, 'None', 59.0, '{"connectivity": "None", "power_source": "Battery powered"}'::jsonb, NULL, 'The Braun ThermoScan 7 Ear Thermometer is a Braun device evaluated in our temperature category.', '["FDA 510(k) Cleared", "Connectivity: None"]'::jsonb, FALSE, FALSE, 1, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'a8de3dca-053c-4548-a2be-d8c2ee16a126'::uuid, id, 1 FROM subcategories WHERE slug = 'thermometers' ON CONFLICT DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'a8de3dca-053c-4548-a2be-d8c2ee16a126'::uuid, id, 1 FROM subcategories WHERE slug = 'in-ear-thermometers' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('e2d8782b-e055-4d81-99fe-249ee6935849', 'a8de3dca-053c-4548-a2be-d8c2ee16a126'::uuid, 'braun-thermoscan-7-hands-on-test', 'MDRank Hands-On Test: Braun ThermoScan 7 Ear Thermometer', 'Independent MDRank evaluation of the Braun ThermoScan 7 Ear Thermometer.', '["Solid performance with score 91/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('9a7409ad-5776-4a76-b5d9-c392506cfa20', 'e2d8782b-e055-4d81-99fe-249ee6935849'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 91/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('c65efb5e-ef36-490f-bc38-e6ad711d5edc', 'ihealth-no-touch-thermometer', 'https://medgrade.org/devices/ihealth-no-touch-thermometer/', 'iHealth No-Touch Forehead Thermometer', 'iHealth', 86, 'fda_510k_cleared'::fda_status, 'None', 35.0, '{"connectivity": "None", "power_source": "Battery powered"}'::jsonb, NULL, 'The iHealth No-Touch Forehead Thermometer is a iHealth device evaluated in our temperature category.', '["FDA 510(k) Cleared", "Connectivity: None"]'::jsonb, FALSE, FALSE, 1, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'c65efb5e-ef36-490f-bc38-e6ad711d5edc'::uuid, id, 1 FROM subcategories WHERE slug = 'thermometers' ON CONFLICT DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT 'c65efb5e-ef36-490f-bc38-e6ad711d5edc'::uuid, id, 1 FROM subcategories WHERE slug = 'infrared-forehead-thermometers' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('2d449b0f-b573-4499-99f9-8ebb04973e7b', 'c65efb5e-ef36-490f-bc38-e6ad711d5edc'::uuid, 'ihealth-no-touch-thermometer-hands-on-test', 'MDRank Hands-On Test: iHealth No-Touch Forehead Thermometer', 'Independent MDRank evaluation of the iHealth No-Touch Forehead Thermometer.', '["Solid performance with score 85/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('3c1e9d0d-23a8-4794-a8ca-ba1532ed3be1', '2d449b0f-b573-4499-99f9-8ebb04973e7b'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 85/100.', 0);

INSERT INTO devices (id, slug, source_url, name, manufacturer, mdrank_score, fda_status, connectivity, retail_price, spec_json, image_url, overview, key_features, is_editors_choice, is_synthetic, rank_in_subcategory, is_published) VALUES ('8c94480b-89f6-4924-9534-c4afcd14d1e0', 'vicks-comfort-flex', 'https://medgrade.org/devices/vicks-comfort-flex/', 'Vicks ComfortFlex Digital Thermometer', 'Vicks', 83, 'fda_registered'::fda_status, 'None', 12.0, '{"connectivity": "None", "power_source": "Battery powered"}'::jsonb, NULL, 'The Vicks ComfortFlex Digital Thermometer is a Vicks device evaluated in our temperature category.', '["FDA Registered", "Connectivity: None"]'::jsonb, FALSE, FALSE, 3, TRUE) ON CONFLICT (slug) DO NOTHING;
INSERT INTO device_subcategories (device_id, subcategory_id, rank) SELECT '8c94480b-89f6-4924-9534-c4afcd14d1e0'::uuid, id, 3 FROM subcategories WHERE slug = 'thermometers' ON CONFLICT DO NOTHING;
INSERT INTO reviews (id, device_id, slug, title, excerpt, strengths, limitations, recommend_if, avoid_if, is_published, published_at) VALUES ('ea1ced0a-722e-41d1-a72b-2455e545d4e3', '8c94480b-89f6-4924-9534-c4afcd14d1e0'::uuid, 'vicks-comfort-flex-hands-on-test', 'MDRank Hands-On Test: Vicks ComfortFlex Digital Thermometer', 'Independent MDRank evaluation of the Vicks ComfortFlex Digital Thermometer.', '["Solid performance with score 82/100", "Reliable for home use"]'::jsonb, '["Feature set varies by model year"]'::jsonb, '["You want a proven option in this category"]'::jsonb, '["You need a different form factor"]'::jsonb, TRUE, NOW()) ON CONFLICT (slug) DO NOTHING;
INSERT INTO review_sections (id, review_id, section_type, heading, body, sort_order) VALUES ('322d08df-0128-47d4-9d7b-e6854312e0f7', 'ea1ced0a-722e-41d1-a72b-2455e545d4e3'::uuid, 'clinical_summary'::review_section_type, 'Clinical Summary', 'MDRank evaluation pending full hands-on test. Source score: 82/100.', 0);

COMMIT;